FIND_PATH(LINUX_OSS_INCLUDE_DIR "linux/soundcard.h"
    HINTS "/usr/include" "/usr/local/include"
)

FIND_PATH(SYS_OSS_INCLUDE_DIR "sys/soundcard.h"
    HINTS "/usr/include" "/usr/local/include"
)

FIND_PATH(MACHINE_OSS_INCLUDE_DIR "machine/soundcard.h"
    HINTS "/usr/include" "/usr/local/include"
)

IF(LINUX_OSS_INCLUDE_DIR)
    SET(OSS_FOUND True)
    SET(OSS_INCLUDE_DIRS ${LINUX_OSS_INCLUDE_DIR})
    SET(OSS_DEFINITIONS HAVE_LINUX_SOUNDCARD_H=1)
ELSEIF(SYS_OSS_INCLUDE_DIR)
    SET(OSS_FOUND True)
    SET(OSS_INCLUDE_DIRS ${SYS_OSS_INCLUDE_DIR})
    SET(OSS_DEFINITIONS HAVE_SYS_SOUNDCARD_H=1)
ELSEIF(MACHINE_OSS_INCLUDE_DIR)
    SET(OSS_FOUND True)
    SET(OSS_INCLUDE_DIRS ${MACHINE_OSS_INCLUDE_DIR})
    SET(OSS_DEFINITIONS HAVE_MACHINE_SOUNDCARD_H=1)
ENDIF()

IF( OSS_FOUND )
    IF( NOT OSS_FIND_QUIETLY )
        MESSAGE( STATUS "Found OSS: \n\tOSS_INCLUDE_DIR: ${OSS_INCLUDE_DIRS}" )
    ENDIF()
ELSE()
    IF( OSS_FIND_REQUIRED )
        MESSAGE( FATAL_ERROR "Could not find OSS")
    ENDIF()
ENDIF()

MARK_AS_ADVANCED(
    OSS_FOUND
    OSS_INCLUDE_DIRS
    OSS_DEFINITIONS
)
